core/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("news.urls")),  
    path("contas/", include("autenticacao.urls")),
    path('criar_conta/', include('contas.urls')),
    path('torneios/', include('torneios.urls')),
    path('esports/', include('esports.urls')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('accounts/', include('allauth.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

esports/urls.py
from django.urls import path
from . import views

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', views.esports, name='esports'),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

news/urls.py
from django.urls import path, include
from . import views

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', views.home, name="home"),
    path('posts/<int:post_id>/post_detail', views.post_detail, name="post_detail"),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

esports/models.py
from django.db import models

# Create your models here.

news/models.py
from ckeditor.fields import RichTextField
from django.db import models
from django.utils import timezone
from ckeditor_uploader.fields import RichTextUploadingField
from contas.models import Perfil
from torneios.models import Game


class Post(models.Model):
    autor = models.CharField(max_length=50)
    titulo = models.CharField(max_length=255)
    game = models.ForeignKey(Game,  on_delete=models.CASCADE, null=True)
    imagem_capa = models.ImageField(null=True, blank=True, upload_to='static/news/')
    data_publicacao = models.DateTimeField(timezone.now())
    def __str__(self):
        return self.titulo

class Tag(models.Model):
    nome = models.CharField(max_length=50)
    posts = models.ManyToManyField(Post) 
    def __str__(self):
        return self.nome
    
class Assunto(models.Model):
    nome = models.CharField(max_length=255)
    posts = models.ManyToManyField(Post)
    
class Situacao(models.Model):
    status = models.CharField(max_length=50)
    posts = models.ManyToManyField(Post, through='PostSituacao', through_fields=('situacao', 'post'))
    def __str__(self):
        return self.status
    
class PostSituacao(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    situacao = models.ForeignKey(Situacao, on_delete=models.CASCADE)
    data = models.DateField(null=True, blank=True)
    
    class Meta:
        unique_together = ['post', 'situacao']

class Topico(models.Model):
    conteudo = RichTextUploadingField(blank=True, null=True)
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    def __str__(self):
        return self.conteudo
    
class Comentario(models.Model):
    texto = models.TextField(max_length=1024)
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    perfil = models.ForeignKey(Perfil, on_delete=models.CASCADE, null=True)
    def __str__(self):
        return self.texto
    
    

esports/views.py
from django.shortcuts import render


# Create your views here.

def esports(request):
   return render(request, 'esports/esports.html')

news/views.py
from django.shortcuts import render
from .models import Post, Topico

# Create your views here.

def home(request):
   posts = Post.objects.order_by('-data_publicacao')[:6]
   context = {
      'posts': posts
   }
   return render(request, 'news/home.html', context)

def post_detail(request, post_id):
   posts = Post.objects.get(pk=post_id)
   context = {
      'posts' : posts
   }
   return render(request, 'news/post_detail.html', context)

news/templates/news/esports.html
{% load static %}

<!DOCTYPE html>
<html lang="pt-br">
    <head>
        <meta charset="UTF-8" />
        <meta http-equiv="X-UA-Compatible" content="IE=edge" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <link rel="stylesheet" href="/css/eSports.css" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link
            href="https://fonts.googleapis.com/css2?family=Roboto:wght@300;400;700&display=swap"
            rel="stylesheet"
        />
        <title>Protto eSports - CS:GO</title>
    </head>
    <body>
        <header class="header">{% include 'fragments/navbar.html' %}</header>

        <img
            class="banner"
            src="/img/banners/csgo.svg"
            alt="Banner com a logo do CS"
        />

        <section class="games">
            <div class="games-container">
                <div class="tournament-name">PGL Major Antwerp 2022</div>
                <div class="versus">
                    <img
                        src="/img/logos-teams/imperial.svg"
                        alt="Logo Imperial"
                    />
                    <a>X</a>
                    <img src="/img/logos-teams/loud.svg" alt="Logo Faze" />
                </div>
                <div class="date-tournament">
                    <div>25/01</div>
                    <div>-</div>
                    <div>16:30</div>
                </div>
            </div>

            <div><hr class="vertical" /></div>

            <div class="games-container">
                <div class="tournament-name">PGL Major Antwerp 2022</div>
                <div class="versus">
                    <img
                        src="/img/logos-teams/imperial.svg"
                        alt="Logo Imperial"
                    />
                    <a>X</a>
                    <img src="/img/logos-teams/loud.svg" alt="Logo Faze" />
                </div>
                <div class="date-tournament">
                    <div>25/01</div>
                    <div>-</div>
                    <div>16:30</div>
                </div>
            </div>

            <div><hr class="vertical" /></div>

            <div class="games-container">
                <div class="tournament-name">PGL Major Antwerp 2022</div>
                <div class="versus">
                    <img
                        src="/img/logos-teams/imperial.svg"
                        alt="Logo Imperial"
                    />
                    <a>X</a>
                    <img src="/img/logos-teams/loud.svg" alt="Logo Faze" />
                </div>
                <div class="date-tournament">
                    <div>25/01</div>
                    <div>-</div>
                    <div>16:30</div>
                </div>
            </div>

            <div><hr class="vertical" /></div>

            <div class="games-container">
                <div class="tournament-name">PGL Major Antwerp 2022</div>
                <div class="versus">
                    <img
                        src="/img/logos-teams/imperial.svg"
                        alt="Logo Imperial"
                    />
                    <a>X</a>
                    <img src="/img/logos-teams/loud.svg" alt="Logo Faze" />
                </div>
                <div class="date-tournament">
                    <div>25/01</div>
                    <div>-</div>
                    <div>16:30</div>
                </div>
            </div>

            <div><hr class="vertical" /></div>

            <div class="games-container">
                <div class="tournament-name">PGL Major Antwerp 2022</div>
                <div class="versus">
                    <img
                        src="/img/logos-teams/imperial.svg"
                        alt="Logo Imperial"
                    />
                    <a>X</a>
                    <img src="/img/logos-teams/loud.svg" alt="Logo Faze" />
                </div>
                <div class="date-tournament">
                    <div>25/01</div>
                    <div>-</div>
                    <div>16:30</div>
                </div>
            </div>

            <div><hr class="vertical" /></div>

            <div class="games-container">
                <div class="tournament-name">PGL Major Antwerp 2022</div>
                <div class="versus">
                    <img
                        src="/img/logos-teams/imperial.svg"
                        alt="Logo Imperial"
                    />
                    <a>X</a>
                    <img src="/img/logos-teams/loud.svg" alt="Logo Faze" />
                </div>
                <div class="date-tournament">
                    <div>25/01</div>
                    <div>-</div>
                    <div>16:30</div>
                </div>
            </div>

            <div><hr class="vertical" /></div>

            <div class="games-container">
                <div class="tournament-name">PGL Major Antwerp 2022</div>
                <div class="versus">
                    <img
                        src="/img/logos-teams/imperial.svg"
                        alt="Logo Imperial"
                    />
                    <a>X</a>
                    <img src="/img/logos-teams/loud.svg" alt="Logo Faze" />
                </div>
                <div class="date-tournament">
                    <div>25/01</div>
                    <div>-</div>
                    <div>16:30</div>
                </div>
            </div>

            <div><hr class="vertical" /></div>

            <div class="games-container">
                <div class="tournament-name">PGL Major Antwerp 2022</div>
                <div class="versus">
                    <img
                        src="/img/logos-teams/imperial.svg"
                        alt="Logo Imperial"
                    />
                    <a>X</a>
                    <img src="/img/logos-teams/loud.svg" alt="Logo Faze" />
                </div>
                <div class="date-tournament">
                    <div>25/01</div>
                    <div>-</div>
                    <div>16:30</div>
                </div>
            </div>
        </section>

        <div class="teams-rank">
            <a>Ranking -</a><a class="letter-green">Teams</a>
        </div>
        <div class="box-ranking">
            <div class="ranking">
                <div class="ranking-container">
                    <div class="position1">1º</div>
                    <div class="teams">
                        <img
                            src="/img/logos-teams/imperial.svg"
                            alt="Logo Imperial"
                        />
                        <a class="team-name">Imperial</a>
                    </div>
                </div>
                <div class="ranking-container">
                    <div class="position2">2º</div>
                    <div class="teams">
                        <img
                            src="/img/logos-teams/imperial.svg"
                            alt="Logo Imperial"
                        />
                        <a class="team-name">Imperial</a>
                    </div>
                </div>
                <div class="ranking-container">
                    <div class="position3">3º</div>
                    <div class="teams">
                        <img
                            src="/img/logos-teams/imperial.svg"
                            alt="Logo Imperial"
                        />
                        <a class="team-name">Imperial</a>
                    </div>
                </div>
                <div class="ranking-container">
                    <div class="positions">4º</div>
                    <div class="teams">
                        <img
                            src="/img/logos-teams/imperial.svg"
                            alt="Logo Imperial"
                        />
                        <a class="team-name">Imperial</a>
                    </div>
                </div>
                <div class="ranking-container">
                    <div class="positions">5º</div>
                    <div class="teams">
                        <img
                            src="/img/logos-teams/imperial.svg"
                            alt="Logo Imperial"
                        />
                        <a class="team-name">Imperial</a>
                    </div>
                </div>
            </div>
        </div>

        <div class="players-rank">
            <a>Ranking -</a><a class="letter-green">Players</a>
        </div>
        <div class="box-ranking">
            <div class="ranking">
                <div class="ranking-container">
                    <div class="position1">1º</div>
                    <div class="teams">
                        <img
                            src="/img/logos-teams/imperial.svg"
                            alt="Logo Imperial"
                        />
                        <a class="team-name">Imperial</a>
                    </div>
                </div>
                <div class="ranking-container">
                    <div class="position2">2º</div>
                    <div class="teams">
                        <img
                            src="/img/logos-teams/imperial.svg"
                            alt="Logo Imperial"
                        />
                        <a class="team-name">Imperial</a>
                    </div>
                </div>
                <div class="ranking-container">
                    <div class="position3">3º</div>
                    <div class="teams">
                        <img
                            src="/img/logos-teams/imperial.svg"
                            alt="Logo Imperial"
                        />
                        <a class="team-name">Imperial</a>
                    </div>
                </div>
                <div class="ranking-container">
                    <div class="positions">4º</div>
                    <div class="teams">
                        <img
                            src="/img/logos-teams/imperial.svg"
                            alt="Logo Imperial"
                        />
                        <a class="team-name">Imperial</a>
                    </div>
                </div>
                <div class="ranking-container">
                    <div class="positions">5º</div>
                    <div class="teams">
                        <img
                            src="/img/logos-teams/imperial.svg"
                            alt="Logo Imperial"
                        />
                        <a class="team-name">Imperial</a>
                    </div>
                </div>
            </div>
        </div>

        <hr class="horizontal" />

        <main>{% include 'news/news.html' %}</main>
        <h1>Notícias</h1>
        <footer class="footer">{% include 'fragments/footer.html' %}</footer>

        <script src="/script.js"></script>
    </body>
</html>

news/templates/news/home.html
<!DOCTYPE html>
{% load static %}
<html lang="pt-br">
    <head>
        <link
            href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css"
            rel="stylesheet"
            integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3"
            crossorigin="anonymous"
        />
        <link
            rel="stylesheet"
            href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css"
        />
        
        <link rel="stylesheet" href="{% static 'css/estilos.css' %}" />
        <link rel="stylesheet" href="{% static 'css/global.css' %}" />
        <script
            src="https://unpkg.com/htmx.org@1.8.0"
            integrity="sha384-cZuAZ+ZbwkNRnrKi05G/fjBX+azI9DNOkNYysZ0I/X5ZFgsmMiBXgDZof30F5ofc"
            crossorigin="anonymous"
        ></script>
        <meta charset="UTF-8" />
        <title>Protto eSports - Home</title>
    </head>

    <body>
        <header class="header">{% include 'fragments/navbar.html' %}</header>
        <section id="menu-games">
            {% include 'fragments/carousel.html' %}
        </section>
        <main>{% include 'news/news.html' %}</main>
        <footer class="footer">{% include 'fragments/footer.html' %}</footer>

        <!-------------------- MICHEL ---------------------
        <div class="container-fluid bg-black">
            <div class="row justify-content-center">
                <div class="col-12">
                    <header class="bg-black">
                        {% include 'fragments/navbar.html' %} {% include
                        'fragments/carousel.html' %}
                    </header>
                </div>
            </div>
        </div>

        <main class="bg-dark">{% include 'news/news.html' %}</main>
        <div class="footer-botom">{% include 'fragments/footer.html' %}</div>
        -->
        <script
            src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"
            integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p"
            crossorigin="anonymous"
        ></script>
    </body>
</html>

news/templates/news/news.html
<section class="feed">
    {% for post in posts %}
    <div class="news">
        <img src="{{ post.imagem_capa.url }}" alt="" />
        <a class="title">{{ post.titulo | safe }}</a>
        <a class="description">{{ post.topico_set.first.conteudo | slice:":300" | safe }} </a>
        <div class="date-author">
            <a class="date">{{ post.data_publicacao | safe }}</a>
            <a class="author">{{ post.autor | safe }}</a>
        </div>
    </div>
    {% endfor %}
</section>

news/templates/news/post_detail.html
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <title>Post Detail</title>
</head>
<body>
    <h1>{{ posts.titulo }}</h1>
    <h3>{{ posts.conteudo }} - {{ posts.autor }} </h3>

    <p>
    {% for topico in post.topico_set.all %}
        {{ topico.conteudo|safe }}
        <br />
    {% endfor %}
    </p>

</body>
</html>